apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: vgz6f82tu-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: vgz6f82tu-go 
  name: vgz6f82tu-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: vgz6f82tu-go 
